apiVersion: apps/v1
kind: Deployment
metadata:
  name: hft-degen-agent
  labels:
    app: hft-degen-agent
    agent-type: degen-trading
spec:
  replicas: 1  # Single replica for high-risk agent
  selector:
    matchLabels:
      app: hft-degen-agent
  template:
    metadata:
      labels:
        app: hft-degen-agent
        agent-type: degen-trading
    spec:
      containers:
      - name: hft-degen-agent
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/hft-images/hft-trader:latest
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
            nvidia.com/gpu: 1  # L4 GPU for ML inference
          limits:
            cpu: "1000m"
            memory: "2Gi"
            nvidia.com/gpu: 1
        env:
        - name: AGENT_TYPE
          value: "degen_trading"
        - name: INITIAL_BALANCE
          value: "10"  # Smaller allocation for degen trading
        - name: GCP_PROJECT_ID
          value: "hft-aster-trader"
        - name: GCP_REGION
          value: "${REGION}"
        - name: LOG_LEVEL
          value: "INFO"
        - name: GPU_ACCELERATION
          value: "true"
        - name: MAX_DAILY_LOSS
          value: "5.0"  # $5 daily loss limit
        - name: TARGET_DAILY_RETURN
          value: "0.05"  # 5% daily target
        - name: SOCIAL_DATA_SOURCES
          value: "twitter,reddit,telegram,dexscreener"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: gemini-api-key
        - name: TWITTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: twitter-api-key
        - name: REDDIT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: reddit-client-id
        - name: REDDIT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: reddit-client-secret
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        # Mount secrets for API keys
        volumeMounts:
        - name: api-keys
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: api-keys
        secret:
          secretName: api-keys
      # Service account for Pub/Sub and other GCP services
      serviceAccountName: hft-agent-sa
      # Node affinity for GPU nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: In
                values:
                - nvidia-l4
      # Tolerations for GPU nodes
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
