# Kubernetes Deployment for the Gemini Sentiment Analyzer Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer
  labels:
    app: sentiment-analyzer
spec:
  replicas: 1 # Only one instance needed for this service
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
      - name: sentiment-analyzer
        # The image will be built and pushed by our Cloud Build pipeline
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/hft-images/sentiment-analyzer:latest
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: GCP_PROJECT_ID
          value: "hft-aster-trader" # Replace with your project ID
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: gemini-api-key
        # - name: NEWS_API_KEY # Optional: if you use a real news API
        #   valueFrom:
        #     secretKeyRef:
        #       name: api-keys
        #       key: news-api-key
      # Use a service account with permissions to publish to Pub/Sub
      serviceAccountName: pubsub-publisher-sa
