# Kubernetes Service for HFT Trading Agents
# Provides internal load balancing and service discovery

apiVersion: v1
kind: Service
metadata:
  name: hft-trading-service
  labels:
    app: hft-trading-agents
spec:
  type: ClusterIP  # Internal only for security
  selector:
    app: hft-trading-agents
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP

---
# Service for Sentiment Analyzer
apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  labels:
    app: sentiment-analyzer
spec:
  type: ClusterIP
  selector:
    app: sentiment-analyzer
  ports:
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP

---
# Headless service for agent discovery
apiVersion: v1
kind: Service
metadata:
  name: hft-agents-headless
  labels:
    app: hft-trading-agents
spec:
  clusterIP: None  # Headless service
  selector:
    app: hft-trading-agents
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
